esphome:
    name: ${devicename}
  

logger:
  level: WARN

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_ssid1
      password: !secret wifi_password1   
    - ssid: !secret wifi_ssid2
      password: !secret wifi_password2      
    
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Fallback Hotspot"
    password: !secret ap_password

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_pass

captive_portal:

web_server:
  port: 80
  include_internal: true
  version: 3

time:
  - platform: homeassistant
    id: my_time

button:
  - platform: restart
    id: reboot
    name: "reboot"
    internal: true