substitutions:
    devicename: "hall-l4-light"

<<: !include common.yaml

esphome:
    name: ${devicename}
    platform: ESP8266
    board: esp01_1m
  
i2c:
    sda: GPIO12
    scl: GPIO14
  
sensor:
    - platform: ade7953_i2c
      irq_pin: GPIO16 # Prevent overheating by setting this
      voltage:
        name: ${devicename} Voltage
        internal: true
      # On the Shelly 2.5 channels are mixed ch1=B ch2=A
      current_a:
        name: ${devicename} Current B
        internal: true
      current_b:
        name: ${devicename} Current A
        internal: true
      active_power_a:
        name: ${devicename} Active Power B
        internal: true
        # active_power_a is normal, so don't multiply by -1
      active_power_b:
        name: ${devicename} Active Power A
        internal: true
        # active_power_b is inverted, so take the absolute value
        filters:
          - lambda: return abs(x);
      update_interval: 60s
  
    # NTC Temperature
    - platform: ntc
      sensor: temp_resistance_reading
      name: ${devicename} Temperature
      unit_of_measurement: "°C"
      accuracy_decimals: 1
      icon: "mdi:thermometer"
      internal: true
      calibration:
        b_constant: 3350
        reference_resistance: 10kOhm
        reference_temperature: 298.15K
    - platform: resistance
      id: temp_resistance_reading
      sensor: temp_analog_reading
      configuration: DOWNSTREAM
      resistor: 32kOhm
      internal: true
    - platform: adc
      id: temp_analog_reading
      pin: A0
      internal: true
  
status_led:
    pin:
      number: GPIO0
      inverted: yes
  
binary_sensor:
    - platform: gpio
      internal: true
      pin:
        number: GPIO13
      name: ${devicename} Switch1
      on_state:
        then:
          - light.toggle: shelly_relay_1
    - platform: gpio
      internal: true
      pin:
        number: GPIO5
      name: ${devicename} Switch2
      on_state:
        then:
          - light.toggle: shelly_relay_2
  
light:
    - platform: binary
      id: shelly_relay_1
      name: Hall L4 Light
      icon: "mdi:ceiling-light"
      internal: false
      restore_mode: RESTORE_DEFAULT_OFF
      output: light_output1
    - platform: binary
      id: shelly_relay_2
      name: Light 2
      icon: "mdi:lightbulb"
      internal: true
      restore_mode: RESTORE_DEFAULT_OFF
      output: light_output2

output:
  - id: light_output1
    platform: gpio
    pin: GPIO04
  - id: light_output2
    platform: gpio
    pin: GPIO15
