substitutions:
  devicename: utilities
  friendly_name: "Electricity and Gas Counter"
  platform: esp32
  board: wemos_d1_mini32

<<: !include common.yaml

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

logger:
  # Serial logging is disabled by setting the logger baud rate to 0.
  # Otherwise the logger will occupy the hardware UART, making it unavailable
  # for receiving smart meter data on pin D7 (GPIO13).
  baud_rate: 0
  level: WARN
  
uart:
  rx_pin: D7
  baud_rate: 115200
  rx_buffer_size: 1500

dsmr:
  request_pin: D5
  request_interval: 10s
  gas_mbus_id: 1

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: ${friendly_name} Energy Delivered Tariff 1
      id: energie_counter_electricity1
      internal: true
      state_class: total_increasing
    energy_delivered_tariff2:
      name: ${friendly_name} Energy Delivered Tariff 2
      id: energie_counter_electricity2
      internal: true
      state_class: total_increasing
    energy_returned_tariff1:
      name: ${friendly_name} Energy Returned Tariff 1
      id: energie_counter_electricity_returned1
      internal: true
      state_class: total_increasing
    energy_returned_tariff2:
      name: ${friendly_name} Energy Returned Tariff 2
      id: energie_counter_electricity_returned2
      internal: true
      state_class: total_increasing
    power_delivered:
      name: ${friendly_name} Power Consumed
      internal: false
      unit_of_measurement: W
      accuracy_decimals: 0
      filters: 
        - multiply: 1000
    power_returned:
      name: ${friendly_name} Power Returned
      internal: false
      unit_of_measurement: W
      accuracy_decimals: 0
      filters: 
        - multiply: 1000
    electricity_failures:
      name: ${friendly_name} Electricity Failures
      internal: true
    electricity_long_failures:
      name: ${friendly_name} Electricity Long Failures
      internal: true
    voltage_l1:
      name: ${friendly_name} Voltage L1
      internal: true
    voltage_l2:
      name: ${friendly_name} Voltage L2
      internal: true
    voltage_l3:
      name: ${friendly_name} Voltage L3
      internal: true
    current_l1:
      id: current_l1
      name: ${friendly_name} Current L1
      internal: false
    current_l2:
      id: current_l2
      name: ${friendly_name} Current L2
      internal: false
    current_l3:
      id: current_l3
      name: ${friendly_name} Current L3
      internal: false
    power_delivered_l1:
      name: ${friendly_name} Power Delivered L1
      internal: true
    power_delivered_l2:
      name: ${friendly_name} Power Delivered L2
      internal: true
    power_delivered_l3:
      name: ${friendly_name} Power Delivered L3
      internal: true
    power_returned_l1:
      name: ${friendly_name} Power Returned L1
      internal: true
    power_returned_l2:
      name: ${friendly_name} Power Returned L2
      internal: true
    power_returned_l3:
      name: ${friendly_name} Power Returned L3
      internal: true
    gas_delivered:
      name: Gas Delivered
      internal: false
      force_update: true

  - platform: template
    name: "Electricity Delivered"
    internal: false
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    unit_of_measurement: "kWh"
    icon: mdi:flash
    lambda: |-
      return id(energie_counter_electricity1).state + id(energie_counter_electricity2).state;
    update_interval: 15s

  - platform: template
    name: "Electricity Returned"
    internal: false
    state_class: total_increasing
    device_class: energy
    accuracy_decimals: 3
    unit_of_measurement: "kWh"
    icon: mdi:flash
    lambda: |-
      return id(energie_counter_electricity_returned1).state + id(energie_counter_electricity_returned2).state;
    update_interval: 15s

text_sensor:
  - platform: dsmr
    identification:
      name: ${friendly_name} Identification  
      internal: true
    p1_version:
      name: ${friendly_name} Version
      internal: true

time:
  - platform: homeassistant
    on_time:
      - cron: '3 30 * * * *'
        then:
          - button.press: reboot
