substitutions:
  devicename: washing-machine
  channel_1: Washing Machine
  platform: esp8266
  board: esp01_1m
  # Higher value gives lower watt readout
  current_res: "0.000943"
  # Lower value gives lower voltage readout
  voltage_div: "2066"
  # measure a relatively strong load and enter values measured by the device vs the values your reference measurement provided here
  power_cal_meas: "1710.0"
  power_cal_real: "1685.0"
  max_power: "2500"
  max_temp: "80.0"
  quintile12: "400"
  quintile23: "8000"
  quintile34: "1200"
  quintile45: "1600"

<<: !include common.yaml
<<: !include common_shellyS.yaml

